-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 14:56:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enderecos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `criado_em` DATETIME NULL DEFAULT NOW(),
  `enderecos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_clientes_enderecos_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_enderecos`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `mydb`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `preco` FLOAT UNSIGNED NOT NULL,
  `categoria` ENUM("Elet", "Coz", "Util", "Limp", "Com") NULL DEFAULT 'Util',
  `marca` VARCHAR(100) NULL,
  `criado_em` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `criado_em` DATETIME NULL DEFAULT NOW(),
  `clientes_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `clientes_id`),
  INDEX `fk_vendas_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `mydb`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quatidade` INT UNSIGNED NOT NULL DEFAULT 1,
  `produtos_id` INT UNSIGNED NOT NULL,
  `vendas_id` INT UNSIGNED NOT NULL,
  `vendas_clientes_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `produtos_id`, `vendas_id`, `vendas_clientes_id`),
  INDEX `fk_vendas_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  INDEX `fk_itens_vendas1_idx` (`vendas_id` ASC, `vendas_clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `mydb`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_vendas1`
    FOREIGN KEY (`vendas_id` , `vendas_clientes_id`)
    REFERENCES `mydb`.`vendas` (`id` , `clientes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
